### ISSUE TITLE
Adding a CBS option shuffles the (already organised) timetable

### ISSUE THREAD

**Issue by benjaminn** [iota-pi/crossangles#14]
When I click to add another CBS option (e.g. Bible study), it would be nice if this was placed on my current timetable without everything else being moved around. At the moment, upon clicking my timetable is reshuffled. Perhaps if there is no available spot for the Bible study it could be put in a blank area, leaving the user to do the reshuffling?

**Comment by bofeiw** [comment]
Yeah, it is better not to reshuffle the existing plan which decreases user experience.

**Comment by iota-pi** [comment]
I've changed the way this works in the beta version (https://next.crossangles.app), and I think it gives a better user-experience. Please let me know what you think!

**Comment by bofeiw** [comment]
@iota-pi 
The new version is indeed a lot better, not reshuffling everything. Two things to note:

1. Selecting "training" option will cause an unrelated tutorial time to be moved.  E.g.
Original timetable: 
<img width="972" alt="Screen Shot 2020-05-02 at 3 28 30 pm" src="https://user-images.githubusercontent.com/34177142/80856055-f3fbe000-8c89-11ea-9396-4c28392d7748.png">
After selecting training, the TUT is moved:
<img width="972" alt="Screen Shot 2020-05-02 at 3 28 31 pm" src="https://user-images.githubusercontent.com/34177142/80856063-0249fc00-8c8a-11ea-8d14-31d1d624db79.png">
Not sure if this is expected, so just pointing it out.



<br><br><br><br>
2. A CSS bug that occurs in Safari. See the screenshot below, there is a line of CSS causing button knot and save as image icon not aligning correctly. Commenting this line out solves the problem. It occurs in Safari 13.1, not occurring in Chrome 81, nor Firefox 75. The live current Cross angle does not have the problem.
<img width="2304" alt="Screen Shot 2020-05-02 at 3 25 28 pm" src="https://user-images.githubusercontent.com/34177142/80856107-653b9300-8c8a-11ea-8f2f-e6aa7bfd5467.png">

<br><br>
Amazing work, thank you!

**Comment by iota-pi** [comment]
Hi Bofei, thanks for the feedback! 
Yes, that's known and intended behaviour. By way of explanation, my attempt has been to keep the automatic timetable update feature (so that as soon as people enter their courses, they can already see a reasonable timetable). But I've prevented the automatic modifications from moving anything that the user has manually positioned.
