### ISSUE TITLE
Early classes can obscure day headings in the downloaded image.

### ISSUE THREAD

**Issue by JackRobbers** [iota-pi/crossangles#15]
To reproduce, pick ENGG1000, COMP2521, and COMP1521. Image downloaded from "save as image" looks like this: 
![timetable(2)](https://user-images.githubusercontent.com/31850261/62407325-d9f97800-b5f9-11e9-9dd6-01bee1a47904.png). The actual webpage looks like this: 
![Screenshot from 2019-08-03 14-23-08](https://user-images.githubusercontent.com/31850261/62407344-42e0f000-b5fa-11e9-9023-d16f05839ba9.png)

**Comment by iota-pi** [comment]
Thanks for the report. Can reproduce, and it happens with other timetables too, with classes that aren't so early, will address this later in the week when I have time

**Comment by iota-pi** [comment]
Fixed on production now
