### ISSUE TITLE
Adding spaces after a course name results in it being unable to be found

### ISSUE THREAD

**Issue by benjaminn** [iota-pi/crossangles#17]
This could be by design, but I noticed that when spaces are added after a course name, the course can no longer be found in the drop-down list. Please see the attached screenshots. 

I assume this could be fixed by stripping all trailing whitespaces from the input. 

![found-course-crossangles](https://user-images.githubusercontent.com/15648842/75002197-b3c4f800-54b7-11ea-8db4-1561e90a25d1.png)
![no-course-found-crossangles](https://user-images.githubusercontent.com/15648842/75002204-b45d8e80-54b7-11ea-809d-23b0b3e664db.png)

**Comment by benjaminn** [comment]
It looks like I was wrong about the simple fix with trimming trailing whitespace (the problem is still there in production). Don't have the time now to investigate how to fix, but could look into it early next week.

**Comment by iota-pi** [comment]
I haven't redeployed yet, I'll do that now

**Comment by iota-pi** [comment]
Done :+1:

**Comment by benjaminn** [comment]
Thanks David - it's working now.

However I've noticed it's now quite slow to type in the text field. Could
there have been a performance drop with this fix?

Could an alternative be to only strip whitespace after no typing has
happened for 0.5s (or a similar length of time)? I haven't done much web
dev before, so don't really know what to suggest!

**Comment by iota-pi** [comment]
Thanks for pointing that out Ben! It works just nicely on my laptop, but I just tested it on my phone and it is a bit sluggish now, I'll look into improving the performance a bit :slightly_smiling_face:

**Comment by iota-pi** [comment]
Okay, I've made a few performance improvements to the course selection. I checked the speed over a few past commits and found that it's actually been slower than I would have liked for a while. It's now feeling much more snappy to me, let me know how it goes for you

**Comment by benjaminn** [comment]
Yep, that's a fair bit faster now. Thanks for following this up so quickly!
