### ISSUE TITLE
Clash allowance

### ISSUE THREAD

**Issue by violetbrina** [iota-pi/crossangles#9]
There are some courses that have clashes built into them (e.g. PHSL2121, BINF3010)
Trying to generate a timetable with them isn't possible since in crossangles no clashes are allowed.

It might be worth adding a clash allowance or check for these classes. Because an initial timetable isn't generated you cannot even adjust the blocks and form your own timetable with the clashes - they simple don't appear.

Here are the examples in bojangles (although I'm certain there are others):
![screen shot 1](https://user-images.githubusercontent.com/9669990/31120143-26c78a30-a87f-11e7-9c02-fd18f68f464c.png)

**Comment by Ltieregenius** [comment]
Hi bro, how do you feel about the course BINF3010? I'm gonna take this course for this sem~

**Comment by iota-pi** [comment]
Hi, and sorry, but this isn't the best place for this discussion. Please try either the [UNSW Discussion Group](https://www.facebook.com/groups/UNSWDiscussionGroup/) on Facebook or the [UNSW subreddit](https://www.reddit.com/r/unsw/)
